apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "clair.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "{{ .Values.service.name }}-api"
    port: {{ .Values.service.externalApiPort }}
    targetPort: {{ .Values.service.internalApiPort }}
    protocol: TCP
  - name: "{{ .Values.service.name }}-health"
    port: {{ .Values.service.externalHealthPort }}
    targetPort: {{ .Values.service.internalHealthPort }}
    protocol: TCP
  selector:
{{ include "clair.matchLabels" $ | indent 4 }}
